# Generated by Django 5.1.4 on 2025-01-06 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstPageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('content', models.JSONField(default=dict, help_text='Stores block-specific content and settings')),
                ('custom_styles', models.JSONField(blank=True, default=dict)),
                ('custom_classes', models.CharField(blank=True, max_length=200)),
                ('block_type', models.CharField(choices=[('hero', 'Hero Section'), ('carousel', 'Image Carousel'), ('text', 'Text Block'), ('contact_form', 'Contact Form'), ('map', 'Google Map'), ('image', 'Single Image'), ('video', 'Video Block')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='first_page/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='first_page/videos/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.firstpageblock')),
            ],
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='blocks/media/')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_page_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='blocks.firstpageblock')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SecondPageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('content', models.JSONField(default=dict, help_text='Stores block-specific content and settings')),
                ('custom_styles', models.JSONField(blank=True, default=dict)),
                ('custom_classes', models.CharField(blank=True, max_length=200)),
                ('block_type', models.CharField(choices=[('program', 'Program Block'), ('faq', 'FAQ Section'), ('pricing', 'Pricing Table'), ('features', 'Features List')], max_length=20)),
                ('icon', models.FileField(blank=True, null=True, upload_to='second_page/icons/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThirdPageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('content', models.JSONField(default=dict, help_text='Stores block-specific content and settings')),
                ('custom_styles', models.JSONField(blank=True, default=dict)),
                ('custom_classes', models.CharField(blank=True, max_length=200)),
                ('block_type', models.CharField(choices=[('partner', 'Partner Block'), ('testimonial', 'Testimonial'), ('gallery', 'Image Gallery'), ('info', 'Information Block')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='third_page/images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ContactBlock',
        ),
        migrations.DeleteModel(
            name='FaqItem',
        ),
        migrations.DeleteModel(
            name='HeroBlock',
        ),
        migrations.DeleteModel(
            name='InfoBlock',
        ),
        migrations.DeleteModel(
            name='PartnerBlock',
        ),
        migrations.DeleteModel(
            name='ProgramBlock',
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='second_page_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='blocks.secondpageblock'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='third_page_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='blocks.thirdpageblock'),
        ),
    ]
